from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


GENERATOR_NOTE = "<!-- Generated by scripts/generate_adapter_docs.py. Edit the generator, not this file. -->"
COMMON_CYCLE = [
    "If this skill is linked or installed at workspace scope, prefer `python .codeagent/skills/lua-nil-review/scripts/run_review_cycle.py refresh`.",
    "Claim exactly one shard with the same wrapper path: `.../run_review_cycle.py claim`.",
    "Review only the shard payload and snippet files. Do not free-read the full repository or giant Lua files unless the finding needs source escalation.",
    "Complete and merge with the same wrapper path: `.../run_review_cycle.py complete --review-json <review.json>`.",
]
REVIEW_JSON_EXAMPLE = """```json
{
  "shard_id": "abc123",
  "reviewer": "codeagent",
  "summary": "One high-confidence nil issue remains.",
  "finding_reviews": [
    {
      "finding_id": "finding-id",
      "decision": "confirm",
      "rationale": "The local variable is assigned nil and reaches string.find without a guard.",
      "severity": "medium"
    }
  ]
}
```"""


@dataclass(frozen=True)
class AdapterDoc:
    filename: str
    intro: str
    extra_note: str
    include_example: bool = False


ADAPTER_DOCS = [
    AdapterDoc(
        filename="CODEAGENT.md",
        intro="Use this repository as the source for a persisted Lua nil-risk review skill on CodeAgent.",
        extra_note="For real use on another repository, prefer `codeagent skills link <repo> --scope workspace` or `codeagent skills install <repo> --scope workspace`, then call the installed wrapper from `.codeagent/skills/lua-nil-review/scripts/`.",
        include_example=True,
    ),
]

LEGACY_DOCS = [
    "AGENTS.md",
    "CLAUDE.md",
    "GEMINI.md",
]


def render_adapter_doc(adapter: AdapterDoc) -> str:
    sections = [
        GENERATOR_NOTE,
        "",
        "# Lua Nil Review",
        "",
        adapter.intro,
        "",
        "## Fast Workflow",
        "",
    ]
    sections.extend([f"{index}. {step}" for index, step in enumerate(COMMON_CYCLE, start=1)])
    sections.extend(
        [
            "",
            "## Notes",
            "",
            f"- {adapter.extra_note}",
            "- Read `references/architecture.md` for visual diagrams of the runtime layers, persisted artifacts, and adapter surfaces.",
            "- `CODEAGENT.md` is the only generated adapter document shipped by this alias build.",
        ]
    )
    if adapter.include_example:
        sections.extend(["", "## Review JSON Example", "", REVIEW_JSON_EXAMPLE])
    sections.append("")
    return "\n".join(sections)


def generated_files(root: Path) -> dict[Path, str]:
    return {root / adapter.filename: render_adapter_doc(adapter) for adapter in ADAPTER_DOCS}


def legacy_files(root: Path) -> list[Path]:
    return [root / filename for filename in LEGACY_DOCS]
