from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


GENERATOR_NOTE = "<!-- Generated by scripts/generate_adapter_docs.py. Edit the generator, not this file. -->"
COMMON_CYCLE = [
    "If this skill is linked or installed at workspace scope, prefer `python .gemini/skills/lua-nil-review/scripts/run_review_cycle.py refresh` and fall back to `.agents/skills/lua-nil-review/scripts/run_review_cycle.py refresh`.",
    "Claim exactly one shard with the same wrapper path: `.../run_review_cycle.py claim`.",
    "Review only the shard payload and snippet files. Do not free-read the full repository or giant Lua files unless the finding needs source escalation.",
    "Complete and merge with the same wrapper path: `.../run_review_cycle.py complete --review-json <review.json>`.",
]
REVIEW_JSON_EXAMPLE = """```json
{
  "shard_id": "abc123",
  "reviewer": "gemini-cli",
  "summary": "One high-confidence nil issue remains.",
  "finding_reviews": [
    {
      "finding_id": "finding-id",
      "decision": "confirm",
      "rationale": "The local variable is assigned nil and reaches string.find without a guard.",
      "severity": "medium"
    }
  ]
}
```"""


@dataclass(frozen=True)
class AdapterDoc:
    filename: str
    intro: str
    extra_note: str
    include_example: bool = False


ADAPTER_DOCS = [
    AdapterDoc(
        filename="AGENTS.md",
        intro="Use the persisted workflow in this repository for large Lua nil-risk reviews.",
        extra_note="Read `references/workflow.md` and `references/configuration.md` when you need the artifact layout or review JSON fields.",
    ),
    AdapterDoc(
        filename="CLAUDE.md",
        intro="Follow the persisted review pipeline instead of reading a giant Lua codebase directly.",
        extra_note="Use `needs_source_escalation` when the current snippet set is not enough. Keep the review incremental and resumable.",
    ),
    AdapterDoc(
        filename="GEMINI.md",
        intro="Use this repository as the source for a persisted Lua nil-risk review skill.",
        extra_note="For real use on another repository, prefer `gemini skills link <repo> --scope workspace` or `gemini skills install <repo> --scope workspace`, then call the installed wrapper from `.gemini/skills/lua-nil-review/scripts/`.",
        include_example=True,
    ),
]


def render_adapter_doc(adapter: AdapterDoc) -> str:
    sections = [
        GENERATOR_NOTE,
        "",
        "# Lua Nil Review",
        "",
        adapter.intro,
        "",
        "## Fast Workflow",
        "",
    ]
    sections.extend([f"{index}. {step}" for index, step in enumerate(COMMON_CYCLE, start=1)])
    sections.extend(["", "## Notes", "", f"- {adapter.extra_note}", "- `agents/openai.yaml` is OpenAI/Codex UI metadata only. Gemini CLI and Claude Code use the root-level instruction files instead."])
    if adapter.include_example:
        sections.extend(["", "## Review JSON Example", "", REVIEW_JSON_EXAMPLE])
    sections.append("")
    return "\n".join(sections)


def generated_files(root: Path) -> dict[Path, str]:
    return {root / adapter.filename: render_adapter_doc(adapter) for adapter in ADAPTER_DOCS}
